[package]
name = "scoped-static"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", optional = true }

[features]
#default = [ "runtime-tokio" ]
runtime-tokio = [ "tokio", "tokio/rt-multi-thread", "tokio/time", "tokio/macros" ]
